-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 20:32:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedding` DEFAULT CHARACTER SET utf8 ;
USE `wedding` ;

-- -----------------------------------------------------
-- Table `wedding`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`group` ;

CREATE TABLE IF NOT EXISTS `wedding`.`group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`branch` ;

CREATE TABLE IF NOT EXISTS `wedding`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT 0,
  `address` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`marital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`marital` ;

CREATE TABLE IF NOT EXISTS `wedding`.`marital` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`employee` ;

CREATE TABLE IF NOT EXISTS `wedding`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_official` TINYINT(1) NULL DEFAULT '0',
  `is_disable` TINYINT(1) NULL DEFAULT '0',
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  `is_active` TINYINT(1) NULL DEFAULT 0,
  `marital_id` INT(11) NULL,
  `branch_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  `code` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `full_name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `birthday` INT(11) NULL DEFAULT NULL,
  `phone` DOUBLE NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL,
  `permanent_residence` VARCHAR(250) NULL COMMENT 'hộ khẩu thường trú',
  `temporary_residence` VARCHAR(250) NULL COMMENT 'hộ khẩu tạm trú',
  `identity_card` VARCHAR(45) NULL COMMENT 'chứng minh nhân dân',
  `education` VARCHAR(45) NULL COMMENT 'học vấn',
  `tax_code` VARCHAR(45) NULL COMMENT 'mã số thuế',
  `coverage_code` VARCHAR(45) NULL COMMENT 'mã sổ bảo hiểm',
  `address` VARCHAR(250) NULL,
  `date_in` INT(11) NULL COMMENT 'ngày làm việc\n',
  `date_out` INT(11) NULL COMMENT 'ngày nghỉ việc',
  `nationality` VARCHAR(45) NULL COMMENT 'quốc tịch',
  `nation` VARCHAR(45) NULL COMMENT 'dân tộc',
  `religiousness` VARCHAR(45) NULL COMMENT 'tôn giáo',
  `health_code` VARCHAR(45) NULL COMMENT 'mã thẻ y tế',
  `gender` TINYINT(1) NULL DEFAULT 0 COMMENT '0 : Nam\n1 : Nữ',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `wedding`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `wedding`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_marital1`
    FOREIGN KEY (`marital_id`)
    REFERENCES `wedding`.`marital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_employee_group1_idx` ON `wedding`.`employee` (`group_id` ASC);

CREATE INDEX `fk_employee_branch1_idx` ON `wedding`.`employee` (`branch_id` ASC);

CREATE INDEX `fk_employee_marital1_idx` ON `wedding`.`employee` (`marital_id` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`user` ;

CREATE TABLE IF NOT EXISTS `wedding`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password_hash` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `auth_key` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` INT(2) NULL DEFAULT '10',
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `token` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `expired_date` INT(11) NULL DEFAULT NULL,
  `created_date` INT(11) NULL DEFAULT NULL,
  `employee_id` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wedding`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_user_employee1_idx` ON `wedding`.`user` (`employee_id` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`category` ;

CREATE TABLE IF NOT EXISTS `wedding`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_home` TINYINT(1) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `is_index` TINYINT(1) NULL DEFAULT '0',
  `is_menu` TINYINT(1) NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NOT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wedding`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_create`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_update`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_category_user1_idx` ON `wedding`.`category` (`user_create` ASC);

CREATE INDEX `fk_category_user2_idx` ON `wedding`.`category` (`user_update` ASC);

CREATE INDEX `fk_category_category1_idx` ON `wedding`.`category` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`product_type` ;

CREATE TABLE IF NOT EXISTS `wedding`.`product_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_type_user1`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_type_user2`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_product_type_user1_idx` ON `wedding`.`product_type` (`user_create` ASC);

CREATE INDEX `fk_product_type_user2_idx` ON `wedding`.`product_type` (`user_update` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`product` ;

CREATE TABLE IF NOT EXISTS `wedding`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_type_id` INT(11) NOT NULL,
  `short_description` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `sale` DOUBLE NULL DEFAULT NULL,
  `discount` DOUBLE NULL DEFAULT NULL,
  `image` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_index` TINYINT(1) NULL DEFAULT NULL,
  `is_home` TINYINT(1) NULL DEFAULT NULL,
  `website` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `lng` DOUBLE NULL DEFAULT NULL,
  `is_view` TINYINT(1) NULL DEFAULT NULL,
  `is_display` TINYINT(1) NULL DEFAULT NULL,
  `rate` DOUBLE NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(10) NULL DEFAULT NULL,
  `start_date_sale` INT(11) NULL DEFAULT NULL,
  `end_date_sale` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_type`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `wedding`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_create_product`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_update_product`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_product_product_type1_idx` ON `wedding`.`product` (`product_type_id` ASC);

CREATE INDEX `fk_product_user1_idx` ON `wedding`.`product` (`user_create` ASC);

CREATE INDEX `fk_product_user2_idx` ON `wedding`.`product` (`user_update` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`color` ;

CREATE TABLE IF NOT EXISTS `wedding`.`color` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_color_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `wedding`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_color_product1_idx` ON `wedding`.`color` (`product_id` ASC);


-- -----------------------------------------------------
-- Table `wedding`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding`.`images` ;

CREATE TABLE IF NOT EXISTS `wedding`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `wedding`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_images_product1_idx` ON `wedding`.`images` (`product_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wedding`.`group`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`group` (`id`, `name`, `role`) VALUES (1, 'Admin', NULL);
INSERT INTO `wedding`.`group` (`id`, `name`, `role`) VALUES (2, 'Nhân sự', NULL);
INSERT INTO `wedding`.`group` (`id`, `name`, `role`) VALUES (3, 'Kế toán', NULL);
INSERT INTO `wedding`.`group` (`id`, `name`, `role`) VALUES (4, 'Bếp', NULL);
INSERT INTO `wedding`.`group` (`id`, `name`, `role`) VALUES (5, 'Kho', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wedding`.`branch`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`branch` (`id`, `name`, `is_delete`, `address`) VALUES (1, 'Chi nhánh 1', 0, NULL);
INSERT INTO `wedding`.`branch` (`id`, `name`, `is_delete`, `address`) VALUES (2, 'Chi nhánh 2', 0, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `wedding`.`marital`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`marital` (`id`, `name`) VALUES (1, 'Độc thân');
INSERT INTO `wedding`.`marital` (`id`, `name`) VALUES (2, 'Có gia đình');
INSERT INTO `wedding`.`marital` (`id`, `name`) VALUES (3, 'Đã ly hôn');
INSERT INTO `wedding`.`marital` (`id`, `name`) VALUES (4, 'Khác');

COMMIT;


-- -----------------------------------------------------
-- Data for table `wedding`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`user` (`id`, `user_name`, `password_hash`, `auth_key`, `status`, `is_admin`, `token`, `expired_date`, `created_date`, `employee_id`, `is_active`) VALUES (1, 'admin', '$2y$13$kN0mQgtwVDRktJBK5N7fPuKTO8kwLfJlrda0KHbeXDJxExwzwHf1.', '17Mto0DdMLwW5j62vGl1d_gZP_mUGw8i', 10, 1, NULL, NULL, NULL, NULL, 0);

COMMIT;

