-- MySQL Script generated by MySQL Workbench
-- 04/19/16 21:28:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wedding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedding` DEFAULT CHARACTER SET utf8 ;
USE `wedding` ;

-- -----------------------------------------------------
-- Table `wedding`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  `address` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `role` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_delete` INT(11) NULL DEFAULT '0',
  `create_date` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`marital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`marital` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_official` TINYINT(1) NULL DEFAULT '0',
  `is_disable` TINYINT(1) NULL DEFAULT '0',
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `marital_id` INT(11) NULL DEFAULT NULL,
  `branch_id` INT(11) NULL DEFAULT NULL,
  `group_id` INT(11) NULL DEFAULT NULL,
  `code` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `full_name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `birthday` INT(11) NULL DEFAULT NULL,
  `phone` DOUBLE NULL DEFAULT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `permanent_residence` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'hộ khẩu thường trú',
  `temporary_residence` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'hộ khẩu tạm trú',
  `identity_card` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'chứng minh nhân dân',
  `education` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'học vấn',
  `tax_code` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'mã số thuế',
  `coverage_code` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'mã sổ bảo hiểm',
  `address` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `date_in` INT(11) NULL DEFAULT NULL COMMENT 'ngày làm việc\n',
  `date_out` INT(11) NULL DEFAULT NULL COMMENT 'ngày nghỉ việc',
  `nationality` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'quốc tịch',
  `nation` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'dân tộc',
  `religiousness` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'tôn giáo',
  `health_code` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'mã thẻ y tế',
  `gender` TINYINT(1) NULL DEFAULT '0' COMMENT '0 : Nam\n1 : Nữ',
  PRIMARY KEY (`id`),
  INDEX `fk_employee_group1_idx` (`group_id` ASC),
  INDEX `fk_employee_branch1_idx` (`branch_id` ASC),
  INDEX `fk_employee_marital1_idx` (`marital_id` ASC),
  CONSTRAINT `fk_employee_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `wedding`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `wedding`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_marital1`
    FOREIGN KEY (`marital_id`)
    REFERENCES `wedding`.`marital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password_hash` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `auth_key` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` INT(2) NULL DEFAULT '10',
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `token` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `expired_date` INT(11) NULL DEFAULT NULL,
  `created_date` INT(11) NULL DEFAULT NULL,
  `employee_id` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_user_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_user_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wedding`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_home` TINYINT(1) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `is_index` TINYINT(1) NULL DEFAULT '0',
  `is_menu` TINYINT(1) NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NOT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_user1_idx` (`user_create` ASC),
  INDEX `fk_category_user2_idx` (`user_update` ASC),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `wedding`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_create`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_update`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`product_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_product_type_user1_idx` (`user_create` ASC),
  INDEX `fk_product_type_user2_idx` (`user_update` ASC),
  CONSTRAINT `fk_product_type_user1`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_type_user2`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_type_id` INT(11) NOT NULL,
  `short_description` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_create` INT(11) NOT NULL,
  `user_update` INT(11) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT '0',
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `price` DOUBLE NULL DEFAULT NULL,
  `sale` DOUBLE NULL DEFAULT NULL,
  `discount` DOUBLE NULL DEFAULT NULL,
  `image` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `is_index` TINYINT(1) NULL DEFAULT NULL,
  `is_home` TINYINT(1) NULL DEFAULT NULL,
  `website` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `lng` DOUBLE NULL DEFAULT NULL,
  `is_view` TINYINT(1) NULL DEFAULT NULL,
  `is_display` TINYINT(1) NULL DEFAULT NULL,
  `rate` DOUBLE NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(10) NULL DEFAULT NULL,
  `start_date_sale` INT(11) NULL DEFAULT NULL,
  `end_date_sale` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_product_type1_idx` (`product_type_id` ASC),
  INDEX `fk_product_user1_idx` (`user_create` ASC),
  INDEX `fk_product_user2_idx` (`user_update` ASC),
  CONSTRAINT `fk_product_type`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `wedding`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_create_product`
    FOREIGN KEY (`user_create`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_update_product`
    FOREIGN KEY (`user_update`)
    REFERENCES `wedding`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`color` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_color_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_color_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `wedding`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_images_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `wedding`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`materia_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`materia_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `update_date` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `is_delete` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`materia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `create_date` INT(11) NULL DEFAULT NULL,
  `update_date` INT(11) NULL DEFAULT NULL,
  `materia_type_id` INT(11) NOT NULL,
  `status` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materia_materia_type1_idx` (`materia_type_id` ASC),
  CONSTRAINT `fk_materia_materia_type1`
    FOREIGN KEY (`materia_type_id`)
    REFERENCES `wedding`.`materia_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `wedding`.`materia_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wedding`.`materia_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_date` INT NULL,
  `update_date` INT NULL,
  `quanlity` INT NULL,
  `description` VARCHAR(255) NULL,
  `status` VARCHAR(255) NULL,
  `price` DOUBLE NULL,
  `total` DOUBLE NULL,
  `marital_id` INT(11) NOT NULL,
  `materia_type_id` INT(11) NOT NULL,
  `branch_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materia_inventory_marital1_idx` (`marital_id` ASC),
  INDEX `fk_materia_inventory_materia_type1_idx` (`materia_type_id` ASC),
  INDEX `fk_materia_inventory_branch1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_materia_inventory_marital1`
    FOREIGN KEY (`marital_id`)
    REFERENCES `wedding`.`marital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_inventory_materia_type1`
    FOREIGN KEY (`materia_type_id`)
    REFERENCES `wedding`.`materia_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_inventory_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `wedding`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wedding`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `wedding`;
INSERT INTO `wedding`.`user` (`id`, `user_name`, `password_hash`, `auth_key`, `status`, `is_admin`, `token`, `expired_date`, `created_date`, `employee_id`, `is_active`) VALUES (1, 'admin', '$13$kN0mQgtwVDRktJBK5N7fPuKTO8kwLfJlrda0KHbeXDJxExwzwHf1.', '17Mto0DdMLwW5j62vGl1d_gZP_mUGw8i', 10, 1, NULL, NULL, NULL, NULL, DEFAULT);

COMMIT;

